---
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [python]

      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        language: system
        types: [yaml]

      - id: markdownlint
        name: markdownlint-cli2
        entry: markdownlint-cli2
        language: system
        types: [markdown]
        files: \.(md|markdown)$
