---
role_name_check: 1

dependency:
  name: galaxy

driver:
  name: docker

lint: ansible-lint

platforms:
  - name: ${MOLECULE_DISTRO:-ubuntu-2404}
    image: 1000bulbs/docker-${MOLECULE_DISTRO:-ubuntu-2404}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: false
      interpreter_python: auto
      pipelining: true
      result_format: yaml
      remote_tmp: /tmp/.ansible/tmp
      timeout: 30
  env:
    ANSIBLE_LOAD_CALLBACK_PLUGINS: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: testinfra
  options:
    sudo: true
    verbose: true
