---
galaxy_info:
  author: Fernando Aleman <faleman@1000bulbs.com>
  description: Role for apt_cache
  license: MIT

  min_ansible_version: "2.17"

  platforms:
    - name: Ubuntu
      version:
        - "2204"
        - "2404"

  galaxy_tags:
    - system

dependencies: []
